### ISSUE TITLE
Peer to peer code review by team 125 The Elmos

### ISSUE THREAD

**Issue by ershadul1** [ershadul1/nytimes-clone#2]
The issues with the project

- The spacing and layout of the page looks different in google chrome

- Excessive use of classes

- The inflation image grid needs proper alignment

- The navbar elements are not aligned properly 

- The iframe is not in the center

- Fonts of the page need change

- The spacing between the paragraphs should be like the original

- The login button in the navbar does not look like the original 

- The bottom covid news bar does not look like the original

**Comment by mohammadumar28** [comment]
Good job! @ershadul1

**Comment by ershadul1** [comment]
Fixed some of the issues
